### ISSUE TITLE
Using REST route to show scanned data.

### ISSUE THREAD

**Issue by ArthurRF** [GigSalad/node-redis-scan#9]
Hey!

I'm trying to use the scanner.scan to make a route that shows all the keys of my redis, but the problem is that the scan does not populate my array even when I use the await before it.
Am I trying to use it wrong?

The code:

`public async getAll(): Promise< any > {
    let allData: string[] = [];

    let test = await scanner.scan('*', (err: any, match: string[]) => {
      if(err) throw(err);

      console.log(match); // This log returns the correct data but only after the route is already closed.
      return match;
    });

    console.log(test); // This log return an empty array.

    return allData;
  }`

Appreciate your help!

**Comment by soundslocke** [comment]
Hi there, @ArthurRF!

It looks like you're trying to use `async`/`await` syntax, but doing so relies upon promises. This library only exposes more traditional error-first callback style functions. There are ways you can "promisify" the various scan functions, but that's [an exercise for the reader](https://nodejs.org/api/util.html#utilpromisifyoriginal). Feel free to search around for "how to promisify" and similar. :slightly_smiling_face: 

So, you cannot `await` the scan functions in this library because they're simply not `async` functions. My guess is your web framework's docs and/or examples probably have some guidance on how to work with error-first callback style functions.

Right now your `getAll()` function is `async` but I'm doubting it needs to be... I'm guessing it can return a `Promise` and that promise can then call `scanner.scan()` and use the callback therein to `resolve()` or `reject()`.

No guarantees, but doing that might look something like this:

```js
public getAll(): Promise< any > {
	return new Promise(function(resolve, reject) {
		scanner.scan('*', (err: any, match: string[]) => {
			if (err) {
				reject(err);
			}
			
			console.log('All matching keys:', match);
			resolve(match);
		}
	}
}
```

Hope that helps.

**Comment by ArthurRF** [comment]
Thanks, @soundslocke !
I didn't implement it yet because it's a secondary task, but when I try to implement I'll search for a way to promisify it and try your method.
